return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		event = { "BufReadPost", "BufNewFile" },
		cmd = { "TSUpdateSync" },
		opts = {
			highlight = { enabled = true },
			indent = { enabled = true },
			ensure_installed = {
				"bash",
				"c",
				"css",
				"fish",
				"html",
				"javascript",
				"json",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"markdown_inline",
				"python",
				"query",
				"regex",
				"rust",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"yaml",
			},
			filetypes = {
				"html",
				"javascript",
				"javascriptreact",
				"lua",
				"typescript",
				"typescriptreact",
			},
		},
	},
	{
		"nvim-treesitter/nvim-treesitter-textobjects",
	},
}
